#!/bin/bash

# Define variables
key_name="school"
bits=4096
passphrase="betty"

# Generate RSA key pair
openssl genrsa -aes256 -passout pass:"$passphrase" -out "$key_name".key "$bits"

# Convert private key to PKCS#8 format
openssl pkcs8 -topk8 -inform PEM -outform PEM -in "$key_name".key -out "$key_name".pkcs8.key -passin pass:"$passphrase"

# Generate public key from private key
openssl rsa -in "$key_name".key -pubout -out "$key_name".pub

# Display success message
echo "RSA key pair created successfully."
